name: "[Chore] 기타 작업"
description: 그외 기타 작업을 위한 이슈 템플릿입니다.
labels: []
title: "[Chore] 작업 내용"
body:
  - type: markdown
    attributes:
      value: |
        ## 🛠️ 작업 내용
        아래 내용을 작성해주세요.

  - type: textarea
    id: task_description
    attributes:
      label: 작업 설명
      description: 수행할 작업 내용을 간단히 작성하세요.
      placeholder: 작업 내용 작성
    validations:
      required: true
